package de.neuefische.todobackend.todo.exceptions;

public record CustomErrorObject( String message ) {
}
